name: Build and Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install gtest
      run: sudo apt install libgtest-dev

    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build . --target install

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release -V
